steps:
  - id: build
    name: gcr.io/cloud-builders/docker@sha256:6c9b879570fe1c63a78af0b575ca5ac52f6c2c7e25f76f91ae1f2d6cb2a872ee
    args:
      - build
      - --pull
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

serviceAccount: projects/$PROJECT_ID/serviceAccounts/synapsegit-build@$PROJECT_ID.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
