use rusqlite::{TransactionBehavior, params};

use crate::decode::{
    attach_review_to_proposal_intent, decode_proposal_intent, load_proposal_intent,
    load_proposal_intent_by_idempotency, load_proposal_intent_by_proposal,
    load_proposal_intent_by_review, load_review, load_review_by_proposal, proposal_intent_tuple,
    review_exists, validate_proposal_intent_review_link,
};
use crate::error::{JournalError, Result};
use crate::types::{
    ProposalIntent, ProposalIntentId, ProposalIntentRegistrationOutcome, ProposalIntentRequest,
    RANDOM_ID_ATTEMPTS, RegisteredProposalIntent, RegisteredReview, ReviewBinding, ReviewId,
    ReviewRecord, ReviewRegistrationOutcome, ReviewState,
};
use crate::validate::{
    digest, validate_control_value, validate_idempotency_key, validate_proposal_intent_request,
};

use super::SqliteReviewJournal;

const PROPOSAL_IDEMPOTENCY_DOMAIN: &[u8] = b"synapsegit-artifact-journal-proposal-idempotency-v2\0";
const PROPOSAL_REQUEST_DOMAIN: &[u8] = b"synapsegit-artifact-journal-proposal-request-v2\0";

impl SqliteReviewJournal {
    /// Durably register the exact private command before Proposal CAS.
    ///
    /// No [`ReviewId`] is generated by this operation. An exact retry in the
    /// same project scope returns the original private intent; reuse of the key
    /// or Proposal identity with changed data fails closed.
    pub fn register_proposal_intent(
        &mut self,
        request: ProposalIntentRequest<'_>,
    ) -> Result<RegisteredProposalIntent> {
        validate_proposal_intent_request(&request)?;
        let idempotency_digest = digest(
            PROPOSAL_IDEMPOTENCY_DOMAIN,
            &[
                request.binding.project_scope().as_bytes(),
                request.idempotency_key,
            ],
        );
        let request_fingerprint = digest(
            PROPOSAL_REQUEST_DOMAIN,
            &[
                request.canonical_request,
                request.artifact_manifest_sha256.as_bytes(),
                request.binding.project_scope().as_bytes(),
                request.binding.proposal_ref_name().as_bytes(),
                request.binding.proposal_head().as_bytes(),
                request.binding.decision_ref_name().as_bytes(),
                request.binding.expected_decision_head().as_bytes(),
            ],
        );
        let transaction = self
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)?;

        if let Some(existing) = load_proposal_intent_by_idempotency(
            &transaction,
            request.binding.project_scope(),
            &idempotency_digest,
        )? {
            if existing.binding == *request.binding
                && existing.request_fingerprint == request_fingerprint
            {
                validate_proposal_intent_review_link(&transaction, &existing)?;
                return Ok(RegisteredProposalIntent {
                    intent: existing,
                    outcome: ProposalIntentRegistrationOutcome::Replayed,
                });
            }
            return Err(JournalError::IdempotencyConflict);
        }
        if let Some(existing) = load_proposal_intent_by_proposal(&transaction, request.binding)? {
            return if existing.binding == *request.binding {
                Err(JournalError::ProposalIntentExists)
            } else {
                Err(JournalError::ReviewBindingConflict)
            };
        }
        if let Some(review) = load_review_by_proposal(&transaction, request.binding)? {
            return if review.binding() == request.binding {
                Err(JournalError::ReviewBindingExists)
            } else {
                Err(JournalError::ReviewBindingConflict)
            };
        }

        for _ in 0..RANDOM_ID_ATTEMPTS {
            let proposal_intent_id = ProposalIntentId::generate()?;
            let inserted = transaction.execute(
                "INSERT OR IGNORE INTO proposal_intents(
                    proposal_intent_id, idempotency_digest, request_fingerprint,
                    artifact_manifest_sha256,
                    project_scope, proposal_ref_name, proposal_head,
                    decision_ref_name, expected_decision_head, review_id
                 ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, NULL)",
                params![
                    proposal_intent_id.as_str(),
                    &idempotency_digest,
                    &request_fingerprint,
                    request.artifact_manifest_sha256,
                    request.binding.project_scope(),
                    request.binding.proposal_ref_name(),
                    request.binding.proposal_head(),
                    request.binding.decision_ref_name(),
                    request.binding.expected_decision_head(),
                ],
            )?;
            if inserted == 1 {
                let intent = ProposalIntent {
                    proposal_intent_id,
                    idempotency_digest,
                    request_fingerprint,
                    artifact_manifest_sha256: request.artifact_manifest_sha256.to_owned(),
                    binding: request.binding.clone(),
                    review_id: None,
                };
                transaction.commit()?;
                return Ok(RegisteredProposalIntent {
                    intent,
                    outcome: ProposalIntentRegistrationOutcome::Created,
                });
            }
            if let Some(existing) = load_proposal_intent_by_idempotency(
                &transaction,
                request.binding.project_scope(),
                &idempotency_digest,
            )? {
                if existing.binding == *request.binding
                    && existing.request_fingerprint == request_fingerprint
                {
                    validate_proposal_intent_review_link(&transaction, &existing)?;
                    return Ok(RegisteredProposalIntent {
                        intent: existing,
                        outcome: ProposalIntentRegistrationOutcome::Replayed,
                    });
                }
                return Err(JournalError::IdempotencyConflict);
            }
            if let Some(existing) = load_proposal_intent_by_proposal(&transaction, request.binding)?
            {
                return if existing.binding == *request.binding {
                    Err(JournalError::ProposalIntentExists)
                } else {
                    Err(JournalError::ReviewBindingConflict)
                };
            }
        }
        Err(JournalError::Random(
            "could not allocate a unique private Proposal intent identifier".into(),
        ))
    }

    /// Finalize a private intent after the caller verifies Proposal publication.
    ///
    /// The supplied binding must exactly equal the stored command. The public
    /// [`ReviewId`] and pending review row are created atomically, and an exact
    /// response-loss retry returns the same locator.
    pub fn commit_proposal_publication(
        &mut self,
        proposal_intent_id: &ProposalIntentId,
        published_binding: &ReviewBinding,
    ) -> Result<RegisteredReview> {
        published_binding.validate()?;
        let transaction = self
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)?;
        let intent = load_proposal_intent(&transaction, proposal_intent_id)?
            .ok_or(JournalError::ProposalIntentNotFound)?;
        if intent.binding() != published_binding {
            return Err(JournalError::ProposalIntentConflict);
        }
        if let Some(review_id) = intent.review_id() {
            let review = load_review(&transaction, review_id)?.ok_or_else(|| {
                JournalError::CorruptData(
                    "finalized Proposal intent references a missing review".into(),
                )
            })?;
            if review.binding() != published_binding {
                return Err(JournalError::CorruptData(
                    "finalized Proposal intent and review binding differ".into(),
                ));
            }
            return Ok(RegisteredReview {
                review,
                outcome: ReviewRegistrationOutcome::Replayed,
            });
        }

        if let Some(existing) = load_review_by_proposal(&transaction, published_binding)? {
            if existing.binding() != published_binding {
                return Err(JournalError::ReviewBindingConflict);
            }
            attach_review_to_proposal_intent(
                &transaction,
                proposal_intent_id,
                existing.review_id(),
            )?;
            transaction.commit()?;
            return Ok(RegisteredReview {
                review: existing,
                outcome: ReviewRegistrationOutcome::Replayed,
            });
        }

        for _ in 0..RANDOM_ID_ATTEMPTS {
            let review_id = ReviewId::generate()?;
            let inserted = transaction.execute(
                "INSERT OR IGNORE INTO reviews(
                    review_id, project_scope, proposal_ref_name, proposal_head,
                    decision_ref_name, expected_decision_head, state
                 ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, 'pending_review')",
                params![
                    review_id.as_str(),
                    published_binding.project_scope(),
                    published_binding.proposal_ref_name(),
                    published_binding.proposal_head(),
                    published_binding.decision_ref_name(),
                    published_binding.expected_decision_head(),
                ],
            )?;
            if inserted == 1 {
                attach_review_to_proposal_intent(&transaction, proposal_intent_id, &review_id)?;
                let review = ReviewRecord {
                    review_id,
                    binding: published_binding.clone(),
                    state: ReviewState::PendingReview,
                };
                transaction.commit()?;
                return Ok(RegisteredReview {
                    review,
                    outcome: ReviewRegistrationOutcome::Created,
                });
            }
            if let Some(existing) = load_review_by_proposal(&transaction, published_binding)? {
                if existing.binding() != published_binding {
                    return Err(JournalError::ReviewBindingConflict);
                }
                attach_review_to_proposal_intent(
                    &transaction,
                    proposal_intent_id,
                    existing.review_id(),
                )?;
                transaction.commit()?;
                return Ok(RegisteredReview {
                    review: existing,
                    outcome: ReviewRegistrationOutcome::Replayed,
                });
            }
        }
        Err(JournalError::Random(
            "could not allocate a unique review identifier".into(),
        ))
    }

    pub fn get_proposal_intent(
        &self,
        proposal_intent_id: &ProposalIntentId,
    ) -> Result<ProposalIntent> {
        let intent = load_proposal_intent(&self.connection, proposal_intent_id)?
            .ok_or(JournalError::ProposalIntentNotFound)?;
        validate_proposal_intent_review_link(&self.connection, &intent)?;
        Ok(intent)
    }

    /// Find a Proposal intent by its private idempotency key within one trusted
    /// project scope.
    ///
    /// The raw key is hashed before SQLite is queried and is never persisted.
    /// Callers must authenticate and authorize `project_scope` before using the
    /// result outside trusted restart orchestration.
    pub fn get_proposal_intent_by_idempotency(
        &self,
        project_scope: &str,
        idempotency_key: &[u8],
    ) -> Result<Option<ProposalIntent>> {
        validate_control_value("project_scope", project_scope)?;
        validate_idempotency_key(idempotency_key)?;
        let idempotency_digest = digest(
            PROPOSAL_IDEMPOTENCY_DOMAIN,
            &[project_scope.as_bytes(), idempotency_key],
        );
        let intent = load_proposal_intent_by_idempotency(
            &self.connection,
            project_scope,
            &idempotency_digest,
        )?;
        if let Some(intent) = intent.as_ref() {
            validate_proposal_intent_review_link(&self.connection, intent)?;
        }
        Ok(intent)
    }

    /// Find an exact private intent from trusted server-owned binding data.
    pub fn get_proposal_intent_by_binding(
        &self,
        binding: &ReviewBinding,
    ) -> Result<Option<ProposalIntent>> {
        binding.validate()?;
        let Some(intent) = load_proposal_intent_by_proposal(&self.connection, binding)? else {
            return Ok(None);
        };
        validate_proposal_intent_review_link(&self.connection, &intent)?;
        Ok((intent.binding() == binding).then_some(intent))
    }

    /// Read the public Proposal manifest digest linked to a durable review.
    ///
    /// Compatibility reviews created through the schema-v1 API have no
    /// Proposal intent and therefore return `None`.
    pub fn get_review_artifact_manifest_sha256(
        &self,
        review_id: &ReviewId,
    ) -> Result<Option<String>> {
        if !review_exists(&self.connection, review_id)? {
            return Err(JournalError::ReviewNotFound);
        }
        let intent = load_proposal_intent_by_review(&self.connection, review_id)?;
        if let Some(intent) = intent.as_ref() {
            validate_proposal_intent_review_link(&self.connection, intent)?;
        }
        Ok(intent.map(|intent| intent.artifact_manifest_sha256))
    }

    /// List private intents still awaiting publication reconciliation.
    ///
    /// This is an internal worker API. The caller must authenticate and scope
    /// `project_scope` before exposing any result outside trusted orchestration.
    pub fn list_unfinalized_proposal_intents(
        &self,
        project_scope: &str,
    ) -> Result<Vec<ProposalIntent>> {
        validate_control_value("project_scope", project_scope)?;
        let mut statement = self.connection.prepare(
            "SELECT proposal_intent_id, idempotency_digest, request_fingerprint,
                    artifact_manifest_sha256,
                    project_scope, proposal_ref_name, proposal_head,
                    decision_ref_name, expected_decision_head, review_id
             FROM proposal_intents
             WHERE project_scope = ?1 AND review_id IS NULL
             ORDER BY proposal_intent_id",
        )?;
        let stored = statement.query_map([project_scope], proposal_intent_tuple)?;
        let mut intents = Vec::new();
        for row in stored {
            intents.push(decode_proposal_intent(row?)?);
        }
        Ok(intents)
    }
}
