#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { execFileSync } from "node:child_process";

const root = process.cwd();
const outputPath = path.join(root, "THIRD_PARTY_NOTICES.md");
const mode = process.argv[2];

if (!new Set(["--check", "--write"]).has(mode)) {
  console.error(
    "usage: node scripts/generate_third_party_notices.mjs --check|--write",
  );
  process.exit(2);
}

const metadata = JSON.parse(
  execFileSync(process.env.CARGO ?? "cargo", [
    "metadata",
    "--locked",
    "--format-version",
    "1",
  ], { encoding: "utf8" }),
);

const packages = metadata.packages
  .filter((pkg) => pkg.source !== null)
  .sort((left, right) =>
    `${left.name}\u0000${left.version}`.localeCompare(
      `${right.name}\u0000${right.version}`,
    ),
  );

const fallbackLicenseFiles = new Map([
  ["uuid-simd@0.8.0", "third_party/Nugine-simd-LICENSE"],
  ["vsimd@0.8.0", "third_party/Nugine-simd-LICENSE"],
]);

function isNoticeFile(filePath, insideLicensesDirectory) {
  if (insideLicensesDirectory) {
    return true;
  }
  return /^(LICENSE|LICENCE|COPYING|COPYRIGHT|UNLICENSE|NOTICE|AUTHORS)([-_.].*)?$/i.test(
    path.basename(filePath),
  );
}

function findNoticeFiles(directory, depth = 0, insideLicensesDirectory = false) {
  const found = [];
  for (const entry of fs
    .readdirSync(directory, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name))) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isFile() && isNoticeFile(entryPath, insideLicensesDirectory)) {
      found.push(entryPath);
    } else if (entry.isDirectory() && depth < 2) {
      const isLicensesDirectory =
        insideLicensesDirectory || /^licenses?$/i.test(entry.name);
      found.push(
        ...findNoticeFiles(entryPath, depth + 1, isLicensesDirectory),
      );
    }
  }
  return found;
}

function normalizeText(content) {
  const lines = content
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.replaceAll("\t", "    ").replace(/[ ]+$/u, ""));
  return `${lines.join("\n").trimEnd()}\n`;
}

function tableCell(value) {
  return String(value ?? "")
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ");
}

const textGroups = new Map();
const missing = [];

for (const pkg of packages) {
  const packageDirectory = path.dirname(pkg.manifest_path);
  let files = findNoticeFiles(packageDirectory);
  const fallback = fallbackLicenseFiles.get(`${pkg.name}@${pkg.version}`);
  if (files.length === 0 && fallback) {
    files = [path.join(root, fallback)];
  }
  if (files.length === 0) {
    missing.push(`${pkg.name}@${pkg.version} (${pkg.license ?? "no license"})`);
    continue;
  }

  for (const file of [...new Set(files)].sort()) {
    const content = normalizeText(fs.readFileSync(file, "utf8"));
    const digest = crypto.createHash("sha256").update(content).digest("hex");
    const reference = `${pkg.name} ${pkg.version} — ${path.basename(file)}`;
    const group = textGroups.get(digest) ?? { content, references: new Set() };
    group.references.add(reference);
    textGroups.set(digest, group);
  }
}

if (missing.length > 0) {
  console.error("third_party_notice_error: missing license/notice text:");
  for (const item of missing) {
    console.error(`- ${item}`);
  }
  process.exit(1);
}

const lines = [
  "# Third-party notices",
  "",
  "This file lists third-party Rust packages resolved by `Cargo.lock` and",
  "reproduces the license, copyright, author, or notice files shipped in their",
  "crate packages. It is generated by",
  "`node scripts/generate_third_party_notices.mjs --write`; do not edit it by",
  "hand.",
  "",
  "The SynapseGit Source-Available License does not replace the terms below.",
  "Each third-party component remains governed by its own license. An entry in",
  "this inventory is not a statement that every target-specific package is",
  "linked into every distributed binary.",
  "",
  "## Package inventory",
  "",
  "| Package | Version | Declared license | Upstream |",
  "|---|---:|---|---|",
];

for (const pkg of packages) {
  lines.push(
    `| ${tableCell(pkg.name)} | ${tableCell(pkg.version)} | ${tableCell(pkg.license ?? "Not declared")} | ${tableCell(pkg.repository ?? pkg.homepage ?? pkg.source)} |`,
  );
}

lines.push("", "## License and notice texts", "");

const groups = [...textGroups.entries()].sort((left, right) => {
  const leftRefs = [...left[1].references].sort().join("\u0000");
  const rightRefs = [...right[1].references].sort().join("\u0000");
  return leftRefs.localeCompare(rightRefs) || left[0].localeCompare(right[0]);
});

for (const [digest, group] of groups) {
  lines.push(`### Notice ${digest.slice(0, 12)}`, "", "Applies to:", "");
  for (const reference of [...group.references].sort()) {
    lines.push(`- ${reference}`);
  }
  lines.push("", `SHA-256: \`${digest}\``, "");
  for (const line of group.content.trimEnd().split("\n")) {
    lines.push(line.length === 0 ? "" : `    ${line}`);
  }
  lines.push("");
}

const generated = `${lines.join("\n").trimEnd()}\n`;

if (mode === "--write") {
  fs.writeFileSync(outputPath, generated);
  console.log(
    `wrote THIRD_PARTY_NOTICES.md for ${packages.length} packages and ${groups.length} unique notice texts`,
  );
} else {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";
  if (current !== generated) {
    console.error(
      "third_party_notice_error: THIRD_PARTY_NOTICES.md is missing or stale; run node scripts/generate_third_party_notices.mjs --write",
    );
    process.exit(1);
  }
  console.log(
    `verified third-party notices for ${packages.length} packages and ${groups.length} unique notice texts`,
  );
}
